// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rfrank
NumericVector rfrank(int n, double theta);
RcppExport SEXP QRM_rfrank(SEXP nSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< double >::type theta(thetaSEXP );
        NumericVector __result = rfrank(n, theta);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rgig
NumericVector rgig(int n, double r, double s, double p, double k1, double k2, double lambda, double chi, double psi, double s1, double s2);
RcppExport SEXP QRM_rgig(SEXP nSEXP, SEXP rSEXP, SEXP sSEXP, SEXP pSEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP lambdaSEXP, SEXP chiSEXP, SEXP psiSEXP, SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< double >::type r(rSEXP );
        Rcpp::traits::input_parameter< double >::type s(sSEXP );
        Rcpp::traits::input_parameter< double >::type p(pSEXP );
        Rcpp::traits::input_parameter< double >::type k1(k1SEXP );
        Rcpp::traits::input_parameter< double >::type k2(k2SEXP );
        Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< double >::type chi(chiSEXP );
        Rcpp::traits::input_parameter< double >::type psi(psiSEXP );
        Rcpp::traits::input_parameter< double >::type s1(s1SEXP );
        Rcpp::traits::input_parameter< double >::type s2(s2SEXP );
        NumericVector __result = rgig(n, r, s, p, k1, k2, lambda, chi, psi, s1, s2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// SEprocExciteFunc
NumericVector SEprocExciteFunc(NumericVector anytimes, NumericVector times, NumericVector marks, double theta, int model);
RcppExport SEXP QRM_SEprocExciteFunc(SEXP anytimesSEXP, SEXP timesSEXP, SEXP marksSEXP, SEXP thetaSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type anytimes(anytimesSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type marks(marksSEXP );
        Rcpp::traits::input_parameter< double >::type theta(thetaSEXP );
        Rcpp::traits::input_parameter< int >::type model(modelSEXP );
        NumericVector __result = SEprocExciteFunc(anytimes, times, marks, theta, model);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
